---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: traefik-ingress-controller
rules:
  - apiGroups:
      - ""
    resources:
      - services
      - endpoints
      - secrets
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - extensions
    resources:
      - ingresses
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - extensions
    resources:
      - ingresses/status
    verbs:
      - update

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: traefik-ingress-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: traefik-ingress-controller
subjects:
  - kind: ServiceAccount
    name: traefik-ingress-controller
    namespace: default

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: traefik-ingress-controller

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: traefik
  labels:
    app: traefik
spec:
  serviceName: traefik
  replicas: 1
  selector:
    matchLabels:
      app: traefik
  template:
    metadata:
      labels:
        app: traefik
    spec:
      serviceAccountName: traefik-ingress-controller
      containers:
        - name: traefik
          image: traefik:v2.2
          args:
            # - --log.level=DEBUG
            - --entrypoints.web.address=:80
            # - --entrypoints.web.http.redirections.entryPoint.to=web-secure
            # - --entrypoints.web.http.redirections.entryPoint.scheme=https
            # - --entrypoints.web-secure.address=:443
            # - --entrypoints.web-secure.http.tls.certResolver=default
            - --providers.kubernetesingress
            - --providers.file.directory=/etc/traefik/dynamic
            - --providers.file.watch
            # - --certificatesResolvers.default.acme.email=tarmiziaffandi@yahoo.com
            # - --certificatesResolvers.default.acme.storage=/root/acme.json
            # - --certificatesResolvers.default.acme.httpChallenge.entryPoint=web
          ports:
            - name: web
              containerPort: 80
            # - name: web-secure
            #   containerPort: 443
          volumeMounts:
            - name: config
              mountPath: /etc/traefik/dynamic
            # - name: data
            #   mountPath: /root
      volumes:
        - name: config
          configMap:
            name: traefik-config
      # nodeSelector:
      #   dedicated: httpd
      # tolerations:
      #   - key: dedicated
      #     operator: Equal
      #     value: httpd
      #     effect: NoSchedule
  # volumeClaimTemplates:
  #   - metadata:
  #       name: data
  #     spec:
  #       accessModes:
  #         - ReadWriteOnce
  #       resources:
  #         requests:
  #           storage: 1Gi

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik-config
data:
  config.yml: |
    http:
      middlewares:
        compressed:
          compress: {}

---
apiVersion: v1
kind: Service
metadata:
  name: traefik
spec:
  type: LoadBalancer
  selector:
    app: traefik
  ports:
    - name: web
      protocol: TCP
      port: 80
      targetPort: 80
    # - name: web-secure
    #   protocol: TCP
    #   port: 443
    #   targetPort: 443
