---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: traefik-ingress-controller
rules:
  - apiGroups:
      - ""
    resources:
      - services
      - endpoints
      - secrets
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - extensions
    resources:
      - ingresses
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - extensions
    resources:
      - ingresses/status
    verbs:
      - update

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: traefik-ingress-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: traefik-ingress-controller
subjects:
  - kind: ServiceAccount
    name: traefik-ingress-controller
    namespace: default

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: traefik-ingress-controller

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: traefik
  labels:
    app: traefik
spec:
  serviceName: traefik
  replicas: 1
  selector:
    matchLabels:
      app: traefik
  template:
    metadata:
      labels:
        app: traefik
    spec:
      serviceAccountName: traefik-ingress-controller
      containers:
        - name: traefik
          image: traefik:v2.2
          args:
            # - --log.level=DEBUG
            - --entrypoints.web.address=:80
            - --providers.kubernetesingress
            - --providers.file.directory=/etc/traefik/dynamic
            - --providers.file.watch
          ports:
            - name: web
              containerPort: 80
          volumeMounts:
            - name: config
              mountPath: /etc/traefik/dynamic
      volumes:
        - name: config
          configMap:
            name: traefik-config

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik-config
data:
  config.yml: |
    http:
      middlewares:
        compressed:
          compress: {}

---
apiVersion: v1
kind: Service
metadata:
  name: traefik
spec:
  type: LoadBalancer
  selector:
    app: traefik
  ports:
    - name: web
      protocol: TCP
      port: 80
      targetPort: 80
